version: 1
name: production-line-v1
objective: deliver long-form technical manuscripts via staged multi-agent orchestration
stages:
  - id: brief
    owner: program_manager
    outputs: [book_brief.md, acceptance_criteria.yaml]
    gate: deterministic
  - id: evidence
    owner: research_synthesis
    outputs: [chapter_evidence/*.md, source_index.csv]
    gate: deterministic
  - id: architecture
    owner: technical_architect
    outputs: [chapter_blueprints/*.md, diagram_specs/*.md]
    gate: deterministic
  - id: draft
    owner: author
    outputs: [chapters/*.md]
    gate: non_deterministic
  - id: review
    owner: review_triad
    outputs: [reviews/*.md]
    gate: deterministic
  - id: revise
    owner: author
    outputs: [chapters_v2/*.md]
    gate: non_deterministic
  - id: visuals
    owner: visual_intelligence
    outputs: [assets/diagrams/*]
    gate: deterministic
  - id: qa
    owner: qa_eval
    outputs: [results/quality_gate.md, results/quality_gate.csv]
    gate: deterministic
  - id: publish
    owner: publishing
    outputs: [release/package_manifest.yaml]
    gate: deterministic
rules:
  - no stage skip
  - all gates must pass before promotion
  - deterministic artifacts required for audit trail
